// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3k2GLz8joD6kgGs32wH5GKpMX1kEiy-Q',
    appId: '1:13389530077:web:9db20fc4ed785543b0ec34',
    messagingSenderId: '13389530077',
    projectId: 'namal-mess-database',
    authDomain: 'namal-mess-database.firebaseapp.com',
    storageBucket: 'namal-mess-database.firebasestorage.app',
    measurementId: 'G-1NGPE4JGJQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCI5qZj-5h2wIZ4DutbSfWwe6vRrtFiBQY',
    appId: '1:13389530077:android:21f5a6e076a889b7b0ec34',
    messagingSenderId: '13389530077',
    projectId: 'namal-mess-database',
    storageBucket: 'namal-mess-database.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBuXulSVEc7_YSzma27HCNzUwj8xjWJVDY',
    appId: '1:13389530077:ios:9ffc7316f951fa85b0ec34',
    messagingSenderId: '13389530077',
    projectId: 'namal-mess-database',
    storageBucket: 'namal-mess-database.firebasestorage.app',
    iosBundleId: 'com.example.untitled123',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBuXulSVEc7_YSzma27HCNzUwj8xjWJVDY',
    appId: '1:13389530077:ios:9ffc7316f951fa85b0ec34',
    messagingSenderId: '13389530077',
    projectId: 'namal-mess-database',
    storageBucket: 'namal-mess-database.firebasestorage.app',
    iosBundleId: 'com.example.untitled123',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD3k2GLz8joD6kgGs32wH5GKpMX1kEiy-Q',
    appId: '1:13389530077:web:d7513f8f49f63587b0ec34',
    messagingSenderId: '13389530077',
    projectId: 'namal-mess-database',
    authDomain: 'namal-mess-database.firebaseapp.com',
    storageBucket: 'namal-mess-database.firebasestorage.app',
    measurementId: 'G-VWRVVT5SER',
  );
}
