// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBRw6hDhXaIcPjv8n6f7GQQ2a9OP20go3U',
    appId: '1:10332678311:web:6a545d57196cafda509382',
    messagingSenderId: '10332678311',
    projectId: 'newnamal-407c8',
    authDomain: 'newnamal-407c8.firebaseapp.com',
    storageBucket: 'newnamal-407c8.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAj-rQ-uTdyzSCzBfJOrIixErHLleaSwAc',
    appId: '1:10332678311:android:9fd89757b91aca56509382',
    messagingSenderId: '10332678311',
    projectId: 'newnamal-407c8',
    storageBucket: 'newnamal-407c8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDOLml8fT2maSVczZZIInflKMza0sumsYs',
    appId: '1:10332678311:ios:2960e78dc0bacaa2509382',
    messagingSenderId: '10332678311',
    projectId: 'newnamal-407c8',
    storageBucket: 'newnamal-407c8.firebasestorage.app',
    iosBundleId: 'com.example.untitled123',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDOLml8fT2maSVczZZIInflKMza0sumsYs',
    appId: '1:10332678311:ios:2960e78dc0bacaa2509382',
    messagingSenderId: '10332678311',
    projectId: 'newnamal-407c8',
    storageBucket: 'newnamal-407c8.firebasestorage.app',
    iosBundleId: 'com.example.untitled123',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBdCCZk8PH7RXxxd5fQmZ1mmloEEqrPzz0',
    appId: '1:10332678311:web:e63508ce5d3b1cb2509382',
    messagingSenderId: '10332678311',
    projectId: 'newnamal-407c8',
    authDomain: 'newnamal-407c8.firebaseapp.com',
    storageBucket: 'newnamal-407c8.firebasestorage.app',
  );

}